# Generated by Django 5.0 on 2026-02-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthdetails',
            name='alcohol_consumption',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthdetails',
            name='betel_quid_use',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthdetails',
            name='diet_intake',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthdetails',
            name='family_history',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthdetails',
            name='hpv_infection',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthdetails',
            name='immune_compromised',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthdetails',
            name='poor_oral_hygiene',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthdetails',
            name='sun_exposure',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patienthealthdetails',
            name='tobacco_use',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patienthealthdetails',
            name='lifestyle_habits',
            field=models.TextField(blank=True, help_text='Optional free text (exercise, habits, diet notes)'),
        ),
        migrations.AlterField(
            model_name='patienthealthdetails',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Patient-described symptoms'),
        ),
        migrations.AlterModelTable(
            name='patienthealthdetails',
            table='tbl_patient_health_details',
        ),
    ]
