# Generated by Django 5.0 on 2026-02-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patienthealthdetails_alcohol_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthealthdetails',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='patienthealthdetails',
            name='weight_kg',
        ),
    ]
