# Generated by Django 5.0 on 2026-02-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_patientlabtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlabtest',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
