# Generated by Django 5.0 on 2026-02-13 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemotherapy',
            fields=[
                ('chemo_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_no', models.IntegerField()),
                ('drug_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('chemo_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
            ],
            options={
                'db_table': 'tbl_chemotherapy',
            },
        ),
        migrations.CreateModel(
            name='Radiotherapy',
            fields=[
                ('radio_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_no', models.IntegerField()),
                ('radiation_type', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('chemo_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
            ],
            options={
                'db_table': 'tbl_radiotherapy',
            },
        ),
    ]
