# Generated by Django 5.0 on 2026-02-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_chemotherapy_radiotherapy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiotherapy',
            old_name='chemo_date',
            new_name='radio_date',
        ),
    ]
