# Generated by Django 5.0 on 2026-02-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_oncologycase_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdoctormessage',
            name='status',
        ),
        migrations.AddField(
            model_name='patientdoctormessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
