# Generated by Django 5.0.8 on 2026-01-31 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_appointment',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=150)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=20)),
            ],
            options={
                'db_table': 'tbl_doctor',
            },
        ),
        migrations.CreateModel(
            name='DoctorDepartment',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tbl_department',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=150)),
                ('license_number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('lab_type', models.CharField(choices=[('Pathology', 'Pathology'), ('Biopsy', 'Biopsy'), ('Oncology', 'Oncology'), ('Dental', 'Dental')], max_length=100)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_lab',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('Usertype', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
        migrations.CreateModel(
            name='ClinicalExamination',
            fields=[
                ('clinical_examination_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesion_appearance', models.TextField(blank=True, null=True)),
                ('ulcer_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('lifestyle_habits', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical', to='myapp.appointment')),
            ],
            options={
                'db_table': 'tbl_clinical_examination',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctordepartment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctordepartment'),
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='myapp.lab')),
            ],
            options={
                'db_table': 'tbl_lab_test',
            },
        ),
        migrations.AddField(
            model_name='lab',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='patients/')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
            options={
                'db_table': 'tbl_patient',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fd_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
            options={
                'db_table': 'tbl_complaint',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
        migrations.CreateModel(
            name='PatientHealthDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('lifestyle_habits', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='health_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patienthealthdetails'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('medicine_details', models.TextField(blank=True, help_text='Medicine name, dosage, duration', null=True)),
                ('medicine_usage', models.TextField(blank=True, help_text='How to use medicine (morning/night, before food etc)', null=True)),
                ('more_details', models.TextField(blank=True, help_text='Extra notes / precautions', null=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='myapp.appointment')),
            ],
            options={
                'db_table': 'tbl_prescription',
            },
        ),
    ]
