# Generated by Django 5.0 on 2026-02-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_patienthealthdetails_height_cm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalexamination',
            name='lesion_appearance',
        ),
        migrations.RemoveField(
            model_name='clinicalexamination',
            name='lifestyle_habits',
        ),
        migrations.RemoveField(
            model_name='clinicalexamination',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='clinicalexamination',
            name='difficulty_swallowing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalexamination',
            name='oral_lesions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalexamination',
            name='pain_intensity',
            field=models.IntegerField(blank=True, help_text='Pain scale from 0 to 10', null=True),
        ),
        migrations.AddField(
            model_name='clinicalexamination',
            name='unexplained_bleeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalexamination',
            name='white_red_patches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clinicalexamination',
            name='ulcer_duration',
            field=models.CharField(blank=True, help_text='Eg: 3 days, 2 weeks', max_length=100, null=True),
        ),
    ]
