# Generated by Django 5.0 on 2026-02-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_patientlabtest_report_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='OncologyCase',
            fields=[
                ('oncology_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_status', models.CharField(choices=[('Suspected', 'Suspected'), ('Confirmed', 'Confirmed'), ('Negative', 'Negative')], default='Suspected', max_length=50)),
                ('stage', models.CharField(blank=True, help_text='Stage I, II, III, IV', max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oncology_case', to='myapp.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
            options={
                'db_table': 'tbl_oncology_case',
            },
        ),
    ]
