# Generated by Django 5.0 on 2026-02-13 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_chemo_date_radiotherapy_radio_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oncologycase',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='oncologycase',
            name='stage',
        ),
        migrations.CreateModel(
            name='PatientDoctorMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Replied', 'Replied')], default='Pending', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
            options={
                'db_table': 'tbl_patient_doctor_message',
                'ordering': ['-date'],
            },
        ),
    ]
